import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface AnalysisData {
  ticker: string;
  recommendation?: string;
  confidenceScore?: number;
  targetPrice?: number;
  currentPrice?: number;
  marketCap?: number;
  createdAt?: string | Date;
  finalReport?: string;
  valuationResult?: string;
  sentimentResult?: string;
  fundamentalResult?: string;
  riskResult?: string;
}

export const generateAnalysisPDF = (data: AnalysisData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // --- Header ---
  doc.setFillColor(10, 10, 10); // Dark background
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(data.ticker.toUpperCase(), 14, 20);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('AI Investment Analysis Report', 14, 30);
  
  const dateStr = data.createdAt 
    ? new Date(data.createdAt).toLocaleDateString() 
    : new Date().toLocaleDateString();
  
  doc.text(dateStr, pageWidth - 14, 20, { align: 'right' });

  // --- Summary Metrics ---
  const yStart = 50;
  
  // Recommendation Box
  const recColor = 
    data.recommendation === 'BUY' ? [34, 197, 94] : // Green
    data.recommendation === 'SELL' ? [239, 68, 68] : // Red
    [234, 179, 8]; // Yellow (Hold)

  doc.setFillColor(recColor[0], recColor[1], recColor[2]);
  doc.roundedRect(14, yStart, 40, 20, 3, 3, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text('RECOMMENDATION', 34, yStart + 6, { align: 'center' });
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(data.recommendation || 'N/A', 34, yStart + 15, { align: 'center' });

  // Metrics Table-like display
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  const formatCurrency = (val?: number) => val ? `$${val.toFixed(2)}` : 'N/A';
  
  doc.text('Current Price:', 70, yStart + 6);
  doc.setFont('helvetica', 'bold');
  doc.text(formatCurrency(data.currentPrice), 100, yStart + 6);

  doc.setFont('helvetica', 'normal');
  doc.text('Target Price:', 70, yStart + 14);
  doc.setFont('helvetica', 'bold');
  doc.text(formatCurrency(data.targetPrice), 100, yStart + 14);

  doc.setFont('helvetica', 'normal');
  doc.text('Confidence Score:', 140, yStart + 6);
  doc.setFont('helvetica', 'bold');
  doc.text(data.confidenceScore ? `${data.confidenceScore}%` : 'N/A', 175, yStart + 6);

  doc.setFont('helvetica', 'normal');
  doc.text('Upside Potential:', 140, yStart + 14);
  doc.setFont('helvetica', 'bold');
  
  const upside = (data.targetPrice && data.currentPrice) 
    ? ((data.targetPrice - data.currentPrice) / data.currentPrice) * 100 
    : null;
    
  doc.setTextColor(upside && upside > 0 ? 34 : 220, upside && upside > 0 ? 197 : 0, 0);
  doc.text(upside ? `${upside > 0 ? '+' : ''}${upside.toFixed(1)}%` : 'N/A', 175, yStart + 14);
  
  // Reset Color
  doc.setTextColor(0, 0, 0);

  // --- Executive Summary ---
  let finalY = yStart + 30;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 14, finalY);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const splitSummary = doc.splitTextToSize(data.finalReport || 'No summary available.', pageWidth - 28);
  doc.text(splitSummary, 14, finalY + 8);
  
  finalY += 10 + (splitSummary.length * 5);

  // --- Detailed Analysis Sections ---
  
  const sections = [
    { title: 'Valuation Analysis', content: data.valuationResult },
    { title: 'Sentiment Analysis', content: data.sentimentResult },
    { title: 'Fundamental Analysis', content: data.fundamentalResult },
    { title: 'Risk Assessment', content: data.riskResult },
  ];

  sections.forEach(section => {
    if (!section.content) return;

    // Check if we need a new page
    if (finalY > 250) {
      doc.addPage();
      finalY = 20;
    }

    finalY += 10;
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setFillColor(240, 240, 240);
    doc.rect(14, finalY - 6, pageWidth - 28, 8, 'F'); // Section header bg
    doc.text(section.title, 16, finalY);
    
    finalY += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const splitContent = doc.splitTextToSize(section.content, pageWidth - 28);
    doc.text(splitContent, 14, finalY);
    
    finalY += (splitContent.length * 5);
  });

  // --- Footer ---
  const footerY = doc.internal.pageSize.height - 20;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    'Disclaimer: This report is generated by AI for informational purposes only. It does not constitute financial advice. ' +
    'Please conduct your own due diligence before making investment decisions.',
    14, footerY, { maxWidth: pageWidth - 28, align: 'center' }
  );

  doc.save(`${data.ticker.toUpperCase()}_Analysis_${new Date().toISOString().split('T')[0]}.pdf`);
};
